#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MODEL_PORT="${DIV3RSA_MODEL_PORT:-8080}"
HEALTH_PATH="${RUNPOD_RUNTIME_HEALTH_PATH:-/health}"
[[ "$HEALTH_PATH" == /* ]] || HEALTH_PATH="/$HEALTH_PATH"

export DIV3RSA_RUNTIME_PROVIDER="${DIV3RSA_RUNTIME_PROVIDER:-runpod}"
export DIV3RSA_RUNTIME_PROVIDER_KIND="${DIV3RSA_RUNTIME_PROVIDER_KIND:-managed}"
export DIV3RSA_RUNTIME_PROVIDER_PRIORITY="${DIV3RSA_RUNTIME_PROVIDER_PRIORITY:-100}"
export DIV3RSA_RUNTIME_PROFILE="${DIV3RSA_RUNTIME_PROFILE:-large_96gb}"
export DIV3RSA_RUNTIME_ALIASES="${DIV3RSA_RUNTIME_ALIASES:-general-prod,code-prod,lab-prod,research-prod}"
export DIV3RSA_START_PROVIDER_BASE_SERVICES="${DIV3RSA_START_PROVIDER_BASE_SERVICES:-${DIV3RSA_START_RUNPOD_BASE_SERVICES:-1}}"

if [[ -n "${RUNPOD_POD_ID:-}" ]]; then
  export DIV3RSA_RUNTIME_EXTERNAL_ID="${DIV3RSA_RUNTIME_EXTERNAL_ID:-$RUNPOD_POD_ID}"
  export DIV3RSA_RUNTIME_PUBLIC_ENDPOINT="${DIV3RSA_RUNTIME_PUBLIC_ENDPOINT:-https://${RUNPOD_POD_ID}-${MODEL_PORT}.proxy.runpod.net/v1}"
  export DIV3RSA_RUNTIME_PUBLIC_HEALTH_URL="${DIV3RSA_RUNTIME_PUBLIC_HEALTH_URL:-https://${RUNPOD_POD_ID}-${MODEL_PORT}.proxy.runpod.net${HEALTH_PATH}}"
fi

exec bash "$SCRIPT_DIR/../runtime/start-production.sh"
